name: Test PSAISuite

on:
  push:
    branches: main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        
    steps:
    - uses: actions/checkout@v4    

    - name: Install Pester
      shell: pwsh
      run: |
        Install-Module -Name Pester -Force -SkipPublisherCheck
        
    - name: Run Tests
      shell: pwsh
      run: |
        cd ./__tests__
        Invoke-Pester -Output Detailed